# Используем официальный образ Python как базовый
FROM python:3.9-slim

# Устанавливаем системные зависимости для работы с PostgreSQL, MongoDB и Redis
RUN apt-get update && \
    apt-get install -y \
    gcc \
    libpq-dev \
    libsasl2-dev \
    python3-dev \
    libssl-dev \
    curl \
    && apt-get clean

# Устанавливаем зависимости Python
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install --no-cache-dir -r requirements.txt

# Копируем все остальные файлы приложения в контейнер
COPY . /app/

# Экспонируем порт для FastAPI
EXPOSE 8000

# Настроим точку входа для запуска FastAPI с помощью Uvicorn
CMD ["uvicorn", "ozon_jwt:app", "--host", "0.0.0.0", "--port", "8000"]
